export const status = [
  { 0: "Not-Started" },
  { 1: "In-Progress" },
  { 2: "Complete" },
];
// export const concept = {
//     Document_identifer:
//         [{
//             CDS_Identifier: value
//         }
//     ]

// }

export const concept = {
  identifier: [
    { 0: "Heart-Cardiac Conditions" },
    { 1: "Blood Sugar Conditions" },
    { 2: "Hyper Tension Condition" },
  ],
};

export const llmAnswer = {
  Concept_LLM_Summary: "This answer is generated by LLM",
  Reference_Text: ["lorem", "sum"],
  Document_Page_Number: [1, 2, 3],
};

export const requirementsData = [
  { requirementName: "Requirement1", requirementStatus: 'true' },
  { requirementName: "Requirement2", requirementStatus: 'false' },
  { requirementName: "Requirement3", requirementStatus: 'true' },
  { requirementName: "Requirement4", requirementStatus: 'false' },
  { requirementName: "Requirement5", requirementStatus: 'false' }
];
