export const status = [{0:'Not Started'}, {1:'In Progress'}, {2:'Complete'}];
// export const concept = {
//     Document_identifer: 
//         [{
//             CDS_Identifier: value
//         }
//     ]

// }

export const concept={
    identifier:[
        {0:'diarehea'},
        {1:'fever'},
        {2:'cough'},
        {3:'sinus'}
]
}

export const llmAnswer={
    Concept_LLM_Summary:"This answer is generated by LLM",
    Reference_Text:["lorem","sum"],
    Document_Page_Number:[1,2,3]
}